### ISSUE TITLE
BED IO ignores score

### ISSUE THREAD

**Issue by charcuterie** [GuttmanLab/guttmanlab-core#20]
The BedIO class returns Gene objects, which have no indication of the BED record score. Perhaps it should return a BedRecord object that contains a Gene? Or be able to return both a Collection<Gene> and a Collection<BedRecord> as needed? (Or an Iterator over them)

I have some BED files in which the score is meaningful, and it was rather frustrating to realize that the BedIO class can't help me.

**Comment by pamelarussell** [comment]
I like the idea of a BEDRecord class with a Gene field. Maybe it could implement a simple interface like this below, and add extra methods to handle the score. That way we could eventually add GFF3 records, or whatever.

public interface AnnotationFileRecord<T extends Annotation> {  
    public T forFormattedString(String formattedString); // Convert file record to Annotation object
    public String toFormattedString(); // Convert annotation object to writeable file record
}

**Comment by charcuterie** [comment]
Pushed changes to master branch this morning. New BEDFileRecord object with updated BEDFileIO.
